import type { CSSProperties } from "react";

export const onirigiriThemeTokenNames = [
  "--onirigiri-action-hover",
  "--onirigiri-background",
  "--onirigiri-compact-control-size",
  "--onirigiri-compact-pane-radius",
  "--onirigiri-compact-toolbar-gap",
  "--onirigiri-compact-toolbar-min-height",
  "--onirigiri-compact-toolbar-padding-block",
  "--onirigiri-compact-toolbar-padding-inline",
  "--onirigiri-control",
  "--onirigiri-control-active-scale",
  "--onirigiri-control-disabled",
  "--onirigiri-control-hover",
  "--onirigiri-control-icon-size",
  "--onirigiri-control-radius",
  "--onirigiri-control-shadow",
  "--onirigiri-control-size",
  "--onirigiri-danger-surface",
  "--onirigiri-danger-text",
  "--onirigiri-divider",
  "--onirigiri-duration-fast",
  "--onirigiri-duration-normal",
  "--onirigiri-easing-standard",
  "--onirigiri-edge",
  "--onirigiri-focus",
  "--onirigiri-focus-border-width",
  "--onirigiri-focus-glow",
  "--onirigiri-focus-outline-offset",
  "--onirigiri-focus-outline-width",
  "--onirigiri-focus-ring-size",
  "--onirigiri-font",
  "--onirigiri-font-mono",
  "--onirigiri-grid",
  "--onirigiri-grid-cell-size",
  "--onirigiri-grid-dot-fade-size",
  "--onirigiri-grid-dot-size",
  "--onirigiri-grid-offset",
  "--onirigiri-icon-stroke-width",
  "--onirigiri-minimap-background",
  "--onirigiri-minimap-border",
  "--onirigiri-minimap-inset",
  "--onirigiri-minimap-pane",
  "--onirigiri-minimap-pane-focused",
  "--onirigiri-minimap-radius",
  "--onirigiri-minimap-resize-size",
  "--onirigiri-minimap-shadow",
  "--onirigiri-minimap-viewport",
  "--onirigiri-minimum-target-size",
  "--onirigiri-muted",
  "--onirigiri-pane",
  "--onirigiri-pane-action-disabled-opacity",
  "--onirigiri-pane-action-radius",
  "--onirigiri-pane-action-size",
  "--onirigiri-pane-actions-gap",
  "--onirigiri-pane-actions-muted-opacity",
  "--onirigiri-pane-focus-shadow",
  "--onirigiri-pane-hover-shadow",
  "--onirigiri-pane-keyboard-focus-shadow",
  "--onirigiri-pane-min-height",
  "--onirigiri-pane-radius",
  "--onirigiri-pane-raised",
  "--onirigiri-pane-shadow",
  "--onirigiri-radius",
  "--onirigiri-radius-pill",
  "--onirigiri-reduced-motion-duration",
  "--onirigiri-resize-focus-outline-offset",
  "--onirigiri-resize-hit-size",
  "--onirigiri-resize-indicator-opacity",
  "--onirigiri-resize-indicator-size",
  "--onirigiri-subtitle-font-size",
  "--onirigiri-text",
  "--onirigiri-title-font-size",
  "--onirigiri-title-font-weight",
  "--onirigiri-title-line-height",
  "--onirigiri-titlebar",
  "--onirigiri-titlebar-compact-min-height",
  "--onirigiri-titlebar-gap",
  "--onirigiri-titlebar-min-height",
  "--onirigiri-titlebar-narrow-padding-inline",
  "--onirigiri-titlebar-padding",
  "--onirigiri-tone",
  "--onirigiri-tone-cyan",
  "--onirigiri-tone-green",
  "--onirigiri-tone-orange",
  "--onirigiri-tone-pink",
  "--onirigiri-tone-ring",
  "--onirigiri-tone-ring-size",
  "--onirigiri-tone-size",
  "--onirigiri-tone-slate",
  "--onirigiri-toolbar",
  "--onirigiri-toolbar-gap",
  "--onirigiri-toolbar-margin",
  "--onirigiri-toolbar-padding",
  "--onirigiri-toolbar-radius",
  "--onirigiri-toolbar-shadow",
  "--onirigiri-touch-control-size",
  "--onirigiri-touch-pane-action-size",
  "--onirigiri-workspace-min-height",
  "--onirigiri-z-focus-ring",
  "--onirigiri-z-minimap",
  "--onirigiri-z-resize",
  "--onirigiri-z-titlebar",
  "--onirigiri-z-toolbar",
] as const;

export type OnirigiriThemeTokenName = (typeof onirigiriThemeTokenNames)[number];
export type OnirigiriThemeTokens = Partial<
  Record<OnirigiriThemeTokenName, string | number>
>;

export const onirigiriThemeTokenGroups = {
  color: [
    "--onirigiri-action-hover",
    "--onirigiri-background",
    "--onirigiri-control",
    "--onirigiri-control-disabled",
    "--onirigiri-control-hover",
    "--onirigiri-danger-surface",
    "--onirigiri-danger-text",
    "--onirigiri-divider",
    "--onirigiri-edge",
    "--onirigiri-focus",
    "--onirigiri-focus-glow",
    "--onirigiri-grid",
    "--onirigiri-minimap-background",
    "--onirigiri-minimap-border",
    "--onirigiri-minimap-pane",
    "--onirigiri-minimap-pane-focused",
    "--onirigiri-minimap-viewport",
    "--onirigiri-muted",
    "--onirigiri-pane",
    "--onirigiri-pane-raised",
    "--onirigiri-text",
    "--onirigiri-titlebar",
    "--onirigiri-tone",
    "--onirigiri-tone-cyan",
    "--onirigiri-tone-green",
    "--onirigiri-tone-orange",
    "--onirigiri-tone-pink",
    "--onirigiri-tone-ring",
    "--onirigiri-tone-slate",
    "--onirigiri-toolbar",
  ],
  elevation: [
    "--onirigiri-control-shadow",
    "--onirigiri-minimap-shadow",
    "--onirigiri-pane-focus-shadow",
    "--onirigiri-pane-hover-shadow",
    "--onirigiri-pane-keyboard-focus-shadow",
    "--onirigiri-pane-shadow",
    "--onirigiri-toolbar-shadow",
  ],
  layout: [
    "--onirigiri-compact-control-size",
    "--onirigiri-compact-toolbar-gap",
    "--onirigiri-compact-toolbar-min-height",
    "--onirigiri-compact-toolbar-padding-block",
    "--onirigiri-compact-toolbar-padding-inline",
    "--onirigiri-control-icon-size",
    "--onirigiri-control-size",
    "--onirigiri-focus-border-width",
    "--onirigiri-focus-outline-offset",
    "--onirigiri-focus-outline-width",
    "--onirigiri-focus-ring-size",
    "--onirigiri-grid-cell-size",
    "--onirigiri-grid-dot-fade-size",
    "--onirigiri-grid-dot-size",
    "--onirigiri-grid-offset",
    "--onirigiri-minimap-inset",
    "--onirigiri-minimap-resize-size",
    "--onirigiri-minimum-target-size",
    "--onirigiri-pane-action-disabled-opacity",
    "--onirigiri-pane-action-size",
    "--onirigiri-pane-actions-gap",
    "--onirigiri-pane-actions-muted-opacity",
    "--onirigiri-pane-min-height",
    "--onirigiri-resize-focus-outline-offset",
    "--onirigiri-resize-hit-size",
    "--onirigiri-resize-indicator-opacity",
    "--onirigiri-resize-indicator-size",
    "--onirigiri-titlebar-compact-min-height",
    "--onirigiri-titlebar-gap",
    "--onirigiri-titlebar-min-height",
    "--onirigiri-titlebar-narrow-padding-inline",
    "--onirigiri-titlebar-padding",
    "--onirigiri-tone-ring-size",
    "--onirigiri-tone-size",
    "--onirigiri-toolbar-gap",
    "--onirigiri-toolbar-margin",
    "--onirigiri-toolbar-padding",
    "--onirigiri-touch-control-size",
    "--onirigiri-touch-pane-action-size",
    "--onirigiri-workspace-min-height",
  ],
  motion: [
    "--onirigiri-control-active-scale",
    "--onirigiri-duration-fast",
    "--onirigiri-duration-normal",
    "--onirigiri-easing-standard",
    "--onirigiri-reduced-motion-duration",
  ],
  shape: [
    "--onirigiri-compact-pane-radius",
    "--onirigiri-control-radius",
    "--onirigiri-minimap-radius",
    "--onirigiri-pane-action-radius",
    "--onirigiri-pane-radius",
    "--onirigiri-radius",
    "--onirigiri-radius-pill",
    "--onirigiri-toolbar-radius",
  ],
  stacking: [
    "--onirigiri-z-focus-ring",
    "--onirigiri-z-minimap",
    "--onirigiri-z-resize",
    "--onirigiri-z-titlebar",
    "--onirigiri-z-toolbar",
  ],
  typography: [
    "--onirigiri-font",
    "--onirigiri-font-mono",
    "--onirigiri-icon-stroke-width",
    "--onirigiri-subtitle-font-size",
    "--onirigiri-title-font-size",
    "--onirigiri-title-font-weight",
    "--onirigiri-title-line-height",
  ],
} as const satisfies Record<string, readonly OnirigiriThemeTokenName[]>;

export type OnirigiriThemeTokenGroup = keyof typeof onirigiriThemeTokenGroups;

export function defineOnirigiriTheme<Theme extends OnirigiriThemeTokens>(
  theme: Theme,
): Theme {
  return theme;
}

export const onirigiriStyleSlots = [
  "control",
  "control-wrap",
  "desktop-controls",
  "grid-cursor",
  "icon",
  "minimap",
  "minimap-resize",
  "pane-picture",
  "pane-placeholder",
  "pane",
  "pane-action",
  "pane-actions",
  "pane-content",
  "pane-heading",
  "pane-live-content",
  "pane-resize-column",
  "pane-resize-row",
  "pane-titlebar",
  "pane-tone",
  "reserved-split",
  "stage",
  "status",
  "toolbar",
  "workspace",
] as const;

export type OnirigiriStyleSlot = (typeof onirigiriStyleSlots)[number];

export const onirigiriStyleStateAttributes = [
  "data-adjusting",
  "data-available",
  "data-cell-kind",
  "data-compact-layout",
  "data-compact-pane-peek",
  "data-corner",
  "data-direction-controls",
  "data-focus-anchor",
  "data-group-selected",
  "data-focused",
  "data-frozen",
  "data-layout",
  "data-maximized",
  "data-moving",
  "data-onirigiri-content-ready",
  "data-onirigiri-picture-ready",
  "data-overview-control",
  "data-overview-progress",
  "data-presentation-mode",
  "data-pane-rearrangement-selection",
  "data-resize-kind",
  "data-runtime-state",
  "data-shortcut-scope",
  "data-tone",
  "data-visible",
] as const;

export type OnirigiriStyleStateAttribute =
  (typeof onirigiriStyleStateAttributes)[number];

export const onirigiriStyleIdentityAttributes = [
  "data-onirigiri-column-id",
  "data-onirigiri-control",
  "data-onirigiri-minimap-pane-id",
  "data-onirigiri-pane-action",
  "data-onirigiri-pane-id",
  "data-onirigiri-surface-kind",
  "data-onirigiri-workspace-id",
] as const;

export type OnirigiriStyleIdentityAttribute =
  (typeof onirigiriStyleIdentityAttributes)[number];

export const onirigiriStylingContract = {
  cascadeLayer: "onirigiri",
  identityAttributes: onirigiriStyleIdentityAttributes,
  slots: onirigiriStyleSlots,
  stateAttributes: onirigiriStyleStateAttributes,
  tokenGroups: onirigiriThemeTokenGroups,
  tokenNames: onirigiriThemeTokenNames,
  version: 8,
} as const;

export type OnirigiriWorkspaceStyle = CSSProperties &
  OnirigiriThemeTokens & {
    [customProperty: `--onirigiri-${string}`]: string | number | undefined;
  };
