import type { OnirigiriPaneDefinition } from "@riteofstring/onirigiri";

import { demoDefinitions } from "./demo-pane";

export const oneDimensionalFixturePanes: readonly OnirigiriPaneDefinition[] = [
  {
    columnId: "signals-column",
    columnWidth: { unit: "px", value: 430 },
    paneId: "signals",
    planeIndex: 0,
    slotIndex: 0,
    surfaceKind: "signals",
    ...demoDefinitions.signals,
  },
  {
    columnId: "focus-column",
    columnWidth: { unit: "px", value: 500 },
    paneId: "tasks",
    planeIndex: 0,
    slotIndex: 1,
    surfaceKind: "tasks",
    weight: 1.15,
    ...demoDefinitions.tasks,
  },
  {
    columnId: "focus-column",
    paneId: "notes",
    planeIndex: 0,
    slotIndex: 1,
    surfaceKind: "notes",
    weight: 0.85,
    ...demoDefinitions.notes,
  },
  {
    columnId: "atlas-column",
    columnWidth: { unit: "px", value: 520 },
    paneId: "atlas",
    planeIndex: 0,
    slotIndex: 2,
    surfaceKind: "atlas",
    ...demoDefinitions.atlas,
  },
  {
    columnId: "system-column",
    columnWidth: { unit: "px", value: 440 },
    paneId: "system",
    planeIndex: 0,
    slotIndex: 3,
    surfaceKind: "system",
    ...demoDefinitions.system,
  },
];

export const twoDimensionalFixturePanes: readonly OnirigiriPaneDefinition[] = [
  {
    columnId: "north-signals-column",
    columnWidth: { unit: "px", value: 430 },
    paneId: "north-signals",
    planeIndex: 0,
    slotIndex: 0,
    surfaceKind: "signals",
    ...demoDefinitions.signals,
  },
  {
    columnId: "north-atlas-column",
    columnWidth: { unit: "px", value: 520 },
    paneId: "north-atlas",
    planeIndex: 0,
    slotIndex: 2,
    surfaceKind: "atlas",
    ...demoDefinitions.atlas,
  },
  {
    columnId: "middle-focus-column",
    columnWidth: { unit: "px", value: 430 },
    paneId: "middle-tasks",
    planeIndex: 1,
    slotIndex: 0,
    surfaceKind: "tasks",
    weight: 1.15,
    ...demoDefinitions.tasks,
  },
  {
    columnId: "middle-focus-column",
    paneId: "middle-notes",
    planeIndex: 1,
    slotIndex: 0,
    surfaceKind: "notes",
    weight: 0.85,
    ...demoDefinitions.notes,
  },
  {
    columnId: "middle-system-column",
    columnWidth: { unit: "px", value: 460 },
    paneId: "middle-system",
    planeIndex: 1,
    slotIndex: 1,
    surfaceKind: "system",
    ...demoDefinitions.system,
  },
  {
    columnId: "south-mixer-column",
    columnWidth: { unit: "px", value: 460 },
    paneId: "south-mixer",
    planeIndex: 2,
    slotIndex: 1,
    surfaceKind: "mixer",
    ...demoDefinitions.mixer,
  },
];
